\documentclass[12pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{longtable}
\usepackage{multirow} 
\usepackage{hyperref}
\usepackage[titles]{tocloft}
\usepackage[affil-it]{authblk}


\setlength\parindent{0pt}

\title{\textbf{\Large Alignment Stats}}

\author {Lucas Michel Todó, Cristina Bancells\\
Alfred Cortes and Juan R. Gonzalez}

\affil{Barcelona Global Health Institute (ISGlobal), Campus PRBB}

\begin{document}
	
\maketitle
\tableofcontents
\newpage

<<include=FALSE>>=
source(file = "~/R/Funcions_1.R")
library(ggplot2)
setwd("~/ISGlobal/TestSet/align_tests/")
@

\section{Importing Data}

First we import the data for every alignment:
<<>>=

####  Fetch files and create iterables ####
file_names <- list.files("./inputs")
file_names <- gsub("_read[12]_sample.fastq", "",file_names)
file_names <- unique(file_names)
dir = "./params_%%/"
params <- c(1:3)
for(element in params){
  gsub("%%", element, dir)
  
}
  
mapq <- read.csv2(file = "./params_1/A7K9_14456_TTAGGC_MAPQ.csv", sep = "\t", header = FALSE)
lens <- read.csv2(file = "./params_1/A7K9_14456_TTAGGC_lengths.csv", sep = "\t", header = FALSE)
lens_something <- read.csv2(file = "./params_1/A7K9_14456_TTAGGC_somethingununmapped_lengths.csv", sep = "\t", header = FALSE)

abs_lens <- abs(as.numeric(lens))
abs_lens_something <- abs(as.numeric(lens_something))
max(as.numeric(lens))
which(lens == 1057118)
purged_lens <- abs_lens
purged_lens[86703:86704] <- c(0,0)
@

\section{Plots}
\subsection{MAPQ}
<<p1, fig.pos="h", fig.cap="Histogram of read's MAPQ">>=
x <- as.data.frame(as.numeric(mapq))
colnames(x) <- "MAPQ"
ggplot(x, aes(x = MAPQ)) +
        geom_histogram(binwidth = 1) +
        labs(x = "MAPQ", y = "Count") +
        scale_x_continuous(breaks = seq(0, 45, by = 2), limits = c(0,48)) +
        scale_y_continuous(breaks = seq(0,35000, by = 2500))

table(x > 5)
@
\clearpage
\subsection{Fragment Length}
<<p2, fig.pos="h", fig.height=4, fig.cap="Histogram of fragment lengths">>=
x <- as.data.frame(purged_lens[purged_lens != 0])
colnames(x) <- "len"
ggplot(x, aes(x = len)) +
        geom_histogram(bins = 100) +
        labs(x = "Lengths", y = "Count") +
        scale_x_continuous(breaks = seq(75, 550, by = 25), limits = c(75,550))
@


And some text after.
\end{document}